/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux paxos 2.6.37.6-24-desktop x86_64"
#define LGL_COMPILED "Sat Dec  1 11:26:09 PST 2012"
#define LGL_RELEASED "Sat Oct 13 14:05:26 CEST 2012"
#define LGL_VERSION "ala"
#define LGL_ID "b02aa1a04343558c4252b5f4a723be021964f652"
