/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define LGL_OS "Linux arrow01 2.6.27.56-0.1-default i686"
#define LGL_COMPILED "Sat Dec  1 18:33:57 PST 2012"
#define LGL_RELEASED "Sat Oct 13 14:05:26 CEST 2012"
#define LGL_VERSION "ala"
#define LGL_ID "b02aa1a04343558c4252b5f4a723be021964f652"
